
export const Ameacas = {
    get
};

function get() {
    let ameacas = [{
        "index": 0,
        "nome": "Wyrven",
        "totalPV": 50,
        "atualPV": 50,
        "totalPM": 25,
        "atualPM": 25,
        "escala": 10,
        "AtributoAtaque": 6,
        "Forca": 2,
        "Habilidade": 4,
        "Resistencia": 3,
        "Armadura": 2,
        "PdF": 6,
    },
    {
        "index": 0,
        "nome": "Wyrven",
        "totalPV": 50,
        "atualPV": 50,
        "totalPM": 25,
        "atualPM": 25,
        "escala": 10,
        "AtributoAtaque": 6,
        "Forca": 2,
        "Habilidade": 4,
        "Resistencia": 3,
        "Armadura": 2,
        "PdF": 6,
    },
    {
        "index": 0,
        "nome": "Wyrven",
        "totalPV": 50,
        "atualPV": 50,
        "totalPM": 25,
        "atualPM": 25,
        "escala": 10,
        "AtributoAtaque": 6,
        "Forca": 2,
        "Habilidade": 4,
        "Resistencia": 3,
        "Armadura": 2,
        "PdF": 6,
    },
    {
        "index": 0,
        "nome": "Wyrven",
        "totalPV": 50,
        "atualPV": 50,
        "totalPM": 25,
        "atualPM": 25,
        "escala": 10,
        "AtributoAtaque": 6,
        "Forca": 2,
        "Habilidade": 4,
        "Resistencia": 3,
        "Armadura": 2,
        "PdF": 6,
    },
    {
        "index": 0,
        "nome": "Wyrven",
        "totalPV": 50,
        "atualPV": 50,
        "totalPM": 25,
        "atualPM": 25,
        "escala": 10,
        "AtributoAtaque": 6,
        "Forca": 2,
        "Habilidade": 4,
        "Resistencia": 3,
        "Armadura": 2,
        "PdF": 6,
    }]

    return ameacas;
}